"use client"
import React, { useEffect, useState } from "react";
import Head from "next/head";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import css from "../styles/Home.module.css"
import axios from "axios";
import Image from 'next/image'
import App from "next/app";


export default function Home() {
  const [user, setUser] = useState([]);
  
  axios.get("http://127.0.0.1:8000/api/produto/").then(function (response) {
    // aqui acessamos o corpo da respawait osta:
    console.log(response.data);
    setUser(response.data) 
  })
  .catch(function (error) {
    // aqui temos acesso ao erro, quando alguma coisa inesperada acontece:

    console.log(error);
  })

  
  console.log(user)
  return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>FastFood Pizza</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="shortcut icon" href="/Logo.png" />
        </Head>
        <main>
         <Hero/>
        </main>
      </div>

      <div className={css.containerPizza}>

<div className={css.imgPizza}>
  {
    user[0]&&
    <Image height={180} width={310} src={user[0]?.imagem}/>
  }
</div>

  <div className={css.imgPizza}>
  {
    user[0]&&
    <Image height={180} width={310} src={user[1]?.imagem}/>
  }
</div>


  <div className={css.imgPizza}>
  {
    user[0]&&
    <Image height={180} width={310} src={user[2]?.imagem}/>
  }
</div>

</div>

<div className={css.infors}>
  <span className={css.inforPizza}>{user[0]?.nome}</span>
  <span className={css.infor2Pizza}>{user[0]?.preco}</span>
  <button className={css.botaoPizza}>ESCOLHER</button>

  <span className={css.inforPizza}>{user[1]?.nome}</span>
  <span className={css.infor2Pizza}>{user[1]?.preco}</span>
  <button className={css.botaoPizza}>ESCOLHER</button>

  <span className={css.inforPizza}>{user[2]?.nome}</span>
  <span className={css.infor2Pizza}>{user[2]?.preco}</span>
  <button className={css.botaoPizza}>ESCOLHER</button>
</div>


<div className={css.containerPizza}>

<div className={css.imgPizza}>
  {
    user[0]&&
    <Image height={180} width={310} src={user[3]?.imagem}/>
  }
</div>

  <div className={css.imgPizza}>
  {
    user[0]&&
    <Image height={180} width={310} src={user[4]?.imagem}/>
  }
</div>

  <div className={css.imgPizza}>
  {
    user[0]&&
    <Image height={180} width={310} src={user[5]?.imagem}/>
  }
</div>
</div>

<div className={css.infors}>
<span className={css.inforPizza}>{user[3]?.nome}</span>
  <span className={css.infor2Pizza}>{user[3]?.preco}</span>
  <button className={css.botaoPizza}>ESCOLHER</button>

  <span className={css.inforPizza}>{user[4]?.nome}</span>
  <span className={css.infor2Pizza}>{user[4]?.preco}</span>
  <button className={css.botaoPizza}>ESCOLHER</button>

  <span className={css.inforPizza}>{user[5]?.nome}</span>
  <span className={css.infor2Pizza}>{user[5]?.preco}</span>
  <button className={css.botaoPizza}>ESCOLHER</button>
</div>

    </Layout>
  );
}