import React from 'react'
import css from '../styles/cadastroentregador.module.css'
import Image from '../node_modules/next/image'
import Logodelivery from '../assets/Logodelivery.png'
import Head from '../node_modules/next/head'
import Link from '../node_modules/next/link'

export default function Header () {
    return(
        
    <div className={css.container2}>
         <Head>
          <title>Login FastFood</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="shortcut icon" href="/Logo.png" />
        </Head>
        <div className={css.containerlogin}>
            <div className={css.wraplogin2}>
                <form className={css.form}>
                    <span className={css.title2}>Realize seu Cadastro</span>
                    <span className={css.titlelittle}>Preencha seus dados</span>

                    <div>
                        <input className={css.wrapinput} type="Nome" placeholder='Nome'/>
                    </div>

                    <div >
                        <input className={css.wrapinput} type="Nome" placeholder='Sobrenome' />
                    </div>

                    <div >
                        <input className={css.wrapinput} type="Email" placeholder='Email' />
                    </div>

                    
                    <div >
                        <input className={css.wrapinput} type="tel" placeholder='Telefone' />
                    </div>

                    <div >
                        <input className={css.wrapinput} type="Nome" placeholder='Endereço' />
                    </div>

                    <div >
                        <input className={css.wrapinput} type="password" placeholder='Senha' />
                    </div>

                    <Link href="/Body"><button className={css.botaoPizza2}>CADASTRAR</button></Link>
                </form>
            </div>
        </div>
        <div className={css.containerlogin}>
            <div className={css.wraplogin}>
                <form className={css.form}>
                    <span className={css.title}>
                    <Image src={Logodelivery} alt="" layout="intrinsic"/>
                        </span>
                    <span className={css.title}>Bem-vindo</span>
                    <span className={css.title3}>de volta!</span>
                    <span className={css.titlelittle2}>Realize seu cadastro agora mesmo.</span>
                </form>
            </div>
        </div>
    </div>
    )
};