import React from 'react'
import css from '../styles/loginentregador.module.css'
import Image from '../node_modules/next/image'
import Logodelivery from '../assets/Logodelivery.png'
import Head from '../node_modules/next/head'
import Link from '../node_modules/next/link'

export default function Header () {
    return(
        
    <div className={css.container2}>
         <Head>
          <title>Login FastFood</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="shortcut icon" href="/Logo.png" />
        </Head>
        <div className={css.containerlogin}>
            <div className={css.wraplogin2}>
                <form className={css.form}>
                    <span className={css.title2}>Faça Login</span>
                    <span className={css.titlelittle}>Preencha seus dados</span>

                    <div>
                        <input className={css.wrapinput} type="Nome" placeholder='Nome'/>
                    </div>

                    <div >
                        <input className={css.wrapinput} type="Email" placeholder='Email' />
                    </div>

                    <Link href="/Bodyentregador"><button className={css.botaoPizza2}>LOGIN</button></Link>
                </form>
            </div>
        </div>
        <div className={css.containerlogin}>
            <div className={css.wraplogin}>
                <form className={css.form}>
                    <span className={css.title}>
                    <Image src={Logodelivery} alt="" layout="intrinsic"/>
                        </span>
                    <span className={css.title}>Bem-vindo</span>
                    <span className={css.title3}>de volta!</span>
                    <span className={css.titlelittle2}>Acesse sua conta agora mesmo.</span>

                    <button className={css.botaoPizza}>LOGIN GOOGLE</button>
                    <span className={css.titlelittle3}>OU</span>
                    <Link href="/cadastroentregador"><button className={css.botaoPizza}>CADASTRE-SE</button></Link>
                </form>
            </div>
        </div>
    </div>
    )
};