import React, { useEffect, useState } from "react";
import Head from "../node_modules/next/head";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import css from "../styles/pedidorealizado.module.css"
import Image from "../node_modules/next/image";
import App from "../node_modules/next/app";
import s1 from '../assets/s1.png'
import Link from "../node_modules/next/link";


export default function Home() {
    
      return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>FastFood Pizza</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="shortcut icon" href="/Logo.png" />
        </Head>
    </div>

    <span className={css.titleText}>
               Seu pedido foi realizado!
      </span>
    
      <span className={css.miniText2}>
      Aguarde de 10 a 30 minutos para sua entrega chegar.
    </span>

    <div className={css.ImageContainer}>
        <Image src={s1} alt="" layout="intrinsic"/>
    </div>

    <Link href="/Body"><button className={css.botaoPizza2}>TELA INICIAL</button></Link>
    </Layout>
    
  );
}