import React, { useEffect, useState } from "react";
import Head from "next/head";
import Layout from "../components/Layout";
import css from "../styles/profile.module.css"


export default function Home() {
  return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>FastFood Pizza</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="shortcut icon" href="/Logo.png" />
        </Head>
      </div>

      <span className={css.titleText}>
               Meu Perfil
      </span>

      <div>
          <input className={css.wrapinput} type="Nome" placeholder='Digite seu Endereço'/>
      </div>

      <div>
          <input className={css.wrapinput} type="Nome" placeholder='Digite o número da sua casa'/>
      </div>

    </Layout>
  );
}