import React, { useEffect, useState } from "react";
import Head from "../node_modules/next/head";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import css from "../styles/bodyentregador.module.css"
import Image from "../node_modules/next/image";
import App from "../node_modules/next/app";


export default function Home() {
    
      return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>FastFood Pizza</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="shortcut icon" href="/Logo.png" />
        </Head>
    </div>
    </Layout>
    
  );
}